export interface ChangelogEntry {
	version: string
	date: string
	type: "feature" | "fix" | "update" | "security" | "release"
	description: string
	details?: string[]
}

export const changelogEntries: ChangelogEntry[] = [
	{
		version: "1.3.34",
		date: "May 17, 2025",
		type: "security",
		description: "Moved to DDoS guard",
		details: [
			"Cloudflare was giving issues with prefetching, DDoS Guard works good now",
			"We will now start updating the changelog page again (we usually forget about it)",
		],
	},
	{
		version: "1.3.33",
		date: "May 16, 2025",
		type: "feature",
		description: "Added IntelX",
		details: ["Added intelx data source", "enhance traceback UX"],
	},
	{
		version: "1.3.31",
		date: "Mar 21, 2025",
		type: "feature",
		description: "Added Vincheck data source, bug fixes",
		details: ["Integrated Vincheck for vehicle history reports", "Fixed traceback module"],
	},
	{
		version: "1.3.30",
		date: "Mar 20, 2025",
		type: "feature",
		description: "Added CallerAPI data source",
		details: ["Integrated CallerAPI for comprehensive phone number intelligence"],
	},
	{
		version: "1.3.29",
		date: "Mar 17, 2025",
		type: "feature",
		description: "Added Advanced Ghunt data source",
		details: ["Integrated Advanced Ghunt with 1B+ records"],
	},
	{
		version: "1.3.28",
		date: "Mar 17, 2025",
		type: "feature",
		description: "Added Rutify and NPD data sources",
		details: ["Integrated Rutify with 8B+ records", "Integrated NPD with 2.9B+ records"],
	},
	{
		version: "1.3.27",
		date: "Mar 16, 2025",
		type: "feature",
		description: "Added Inf0sec data source",
		details: ["Integrated Inf0sec with 5B+ records"],
	},
	{
		version: "1.3.26",
		date: "Mar 16, 2025",
		type: "feature",
		description: "Added LeakCheck data source",
		details: ["Integrated LeakCheck with 9.1B+ records", "Enhanced data breach search capabilities"],
	},
	{
		version: "1.3.25",
		date: "Mar 15, 2025",
		type: "feature",
		description: "Added IntelFetch data source",
		details: ["Added IntelFetch as another data source", "Improved search capabilities"],
	},
	{
		version: "1.3.24",
		date: "Mar 14, 2025",
		type: "feature",
		description: "Added IntelX data source",
		details: ["Added IntelX as another data source", "Expanded search capabilities with 207.28B+ records"],
	},
	{
		version: "1.3.23",
		date: "Mar 09, 2025",
		type: "feature",
		description: "Added custom Discord ID module",
		details: ["Added a Discord ID module that queries multiple data sources"],
	},
	{
		version: "1.3.22",
		date: "Mar 09, 2025",
		type: "feature",
		description: "Added Oathnet data source",
		details: ["Added Oathnet as another data source", "Added better ratelimits"],
	},
	{
		version: "1.3.21",
		date: "Mar 08, 2025",
		type: "security",
		description: "Improved antibot",
		details: ["Added hCAPTCHA to sign-up and sign-in pages", "Added better ratelimits"],
	},
	{
		version: "1.3.20",
		date: "Mar 07, 2025",
		type: "feature",
		description: "Added Traceback.sh",
		details: [
			"Added Traceback.sh as another data source",
			"Alert message redesigned",
			"Redesigned intelligence matrix to be less polluted",
		],
	},
	{
		version: "1.3.19",
		date: "Mar 05, 2025",
		type: "feature",
		description: "Added OSINT.Industries data source",
		details: [
			"Added OSINT Industries as another data source. OSINT Industries PDFs are generated by us",
			"Sidebar is now scrollable",
		],
	},
	{
		version: "1.3.18",
		date: "Mar 05, 2025",
		type: "feature",
		description: "Added Hunter.io data source",
		details: ["Added Hunter.io as another data source. Very useful for public people", "Sidebar is now scrollable"],
	},
	{
		version: "1.3.17",
		date: "Mar 03, 2025",
		type: "update",
		description: "Made OSINT Alternative Free",
		details: ["OSINT Alternative is now free for all users"],
	},
	{
		version: "1.3.16",
		date: "Mar 03, 2025",
		type: "feature",
		description: "Added IntelVault",
		details: ["Added IntelVault data source. "],
	},
	{
		version: "1.3.15",
		date: "Mar 02, 2025",
		type: "update",
		description: "TOS and Privacy",
		details: ["Added privacy and Terms Of Service pages"],
	},
	{
		version: "1.3.14",
		date: "Mar 02, 2025",
		type: "fix",
		description: "Improved error logging",
		details: ["Error when making a query without a subscription now states that fact"],
	},
	{
		version: "1.3.13",
		date: "Mar 01, 2025",
		type: "feature",
		description: "Enabled auto-buy functionality on-site",
		details: ["Users can now auto-purchase services directly on tracked.sh"],
	},
	{
		version: "1.3.12",
		date: "Feb 28, 2025",
		type: "update",
		description: "Enhanced search capabilities and UI improvements",
		details: [
			"Added Endato person search",
			"Implemented KeyScore UUID and regex search",
			"Redesigned search box for improved user flow",
		],
	},
	{
		version: "1.3.11",
		date: "Feb 26, 2025",
		type: "feature",
		description: "Added IP address analysis for Snusbase results",
		details: [
			"Analyzes IP addresses to provide general location insights",
			"Aids investigations on targets with common names",
			"Note: VPN data may be unreliable",
		],
	},
	{
		version: "1.3.10",
		date: "Feb 25, 2025",
		type: "feature",
		description: "Integrated ENDATO data source",
		details: ["Added ENDATO integration for expanded data coverage", "Introduced additional search operators"],
	},
	{
		version: "1.3.09",
		date: "Feb 25, 2025",
		type: "update",
		description: "Removed OSINT.Industries and added alternative OSINT service",
		details: [
			"OSINT.Industries removed due to instability",
			"Integrated an alternative OSINT service with limited modules",
		],
	},
	{
		version: "1.3.08",
		date: "Feb 25, 2025",
		type: "feature",
		description: "Enhanced KeyScore export functionality",
		details: [
			"Now exports to JSON, USER:PASS, and URL:USER:PASS formats",
			"Processing completed entirely in the browser",
		],
	},
	{
		version: "1.3.07",
		date: "Feb 22, 2025",
		type: "update",
		description: "Improved Snusbase integration and added SEON Search By IP",
		details: [
			"Added an additional Snusbase API key to mitigate rate limits",
			"Enabled SEON-based IP search for targeted investigations",
		],
	},
	{
		version: "1.3.06",
		date: "Feb 19, 2025",
		type: "feature",
		description: "Integrated SEON data source",
		details: ["Expanded data acquisition with SEON integration"],
	},
	{
		version: "1.3.05",
		date: "Feb 18, 2025",
		type: "feature",
		description: "Reinstated OSINT.Industries integration (usernames only)",
		details: ["OSINT.Industries is back with a scraping solution for usernames"],
	},
	{
		version: "1.3.04",
		date: "Feb 14, 2025",
		type: "update",
		description: "Removed IntelGain integration",
		details: ["IntelGain data source removed from the platform"],
	},
	{
		version: "1.3.03",
		date: "Feb 01, 2025",
		type: "update",
		description: "Updated website theme",
		details: ["Revamped website design for improved user experience"],
	},
	{
		version: "1.3.02",
		date: "Jan 31, 2025",
		type: "feature",
		description: "Integrated OSINTCat data source",
		details: ["Added OSINTCat integration for enhanced data retrieval"],
	},
	{
		version: "1.3.01",
		date: "Jan 30, 2025",
		type: "feature",
		description: "Integrated TGScan data source",
		details: ["Added TGScan integration for messaging platform data analysis"],
	},
	{
		version: "1.3.00",
		date: "Jan 26, 2025",
		type: "release",
		description: "Platform release",
		details: ["Initial release of TRACKED Intelligence Matrix"],
	},
	{
		version: "1.5.0",
		date: "2023-10-08",
		type: "feature",
		description: "Added Advanced Ghunt data source",
		details: ["Integrated Advanced Ghunt with 1B+ records"],
	},
]

export const getLatestVersion = (): string => {
	return changelogEntries[0].version
}

export const getRecentChangelogs = (limit = 5): ChangelogEntry[] => {
	return changelogEntries.slice(0, limit)
}
