import type { LucideIcon } from "lucide-react"
import {
	CatIcon,
	Fingerprint,
	Home,
	Mail,
	SearchCheck,
	FileText,
	Clock,
	CreditCard,
	VaultIcon,
	SearchCode,
	BugIcon,
	User,
	Database,
	Globe,
	Layers,
	UserCircle,
	CheckCheckIcon,
	Eye,
	Check,
	Target,
	MapPin,
	Drill,
	Dog,
	Radar,
	UserSearch,
	Twitter,
	PawPrint,
} from "lucide-react"
import { IconUniverse } from "@tabler/icons-react"
import { SnusbaseIcon } from "@/components/icons/SnusbaseIcon"
import { EndatoIcon } from "@/components/icons/EndatoIcon"
import { HunterIcon } from "@/components/icons/HunterIcon"
import { LeakCheckIcon } from "@/components/icons/LeakCheckIcon"
import NPDIcon from "@/components/icons/NPDIcon"
import RutifyIcon from "@/components/icons/RutifyIcon"
import { ShodanIcon } from "@/components/icons"
import { CallerAPIIcon } from "@/components/icons"
import { CarfaxIcon } from "@/components/icons/CarfaxIcon"
import { LeakSightIcon } from "@/components/icons/LeakSightIcon"
import { IntelligenceXIcon } from "@/components/icons/IntelxIcon"

export type DataSourceStatus = "active" | "updating" | "offline"

export type DataSourceCategory = {
	name: string
	icon: LucideIcon
	description?: string
}

export type DataSource = {
	id: string
	name: string
	icon: LucideIcon | React.ComponentType
	description: string
	category: string
	isPopular?: boolean
	isNew?: boolean
	isFree?: boolean
	path: string
	requiresAuth?: boolean
	isPremium?: boolean
	tags?: string[]

	status: DataSourceStatus
	records: string
	lastVerified: string

	price?: string
	priceType?: "one-time" | "monthly" | "yearly" | "per-report"
}

export const DATA_SOURCE_CATEGORIES: Record<string, DataSourceCategory> = {
	dashboard: {
		name: "Dashboard",
		icon: Home,
		description: "System overview and status monitor",
	},
	breachData: {
		name: "Breach Data",
		icon: Database,
		description: "Data breach and credential leak sources",
	},
	osintTools: {
		name: "OSINT Tools",
		icon: Globe,
		description: "Open source intelligence tools",
	},
	specializedData: {
		name: "Specialized Data",
		icon: Layers,
		description: "Specialized data sources and services",
	},
	account: {
		name: "Account",
		icon: UserCircle,
		description: "Account management and settings",
	},
	resources: {
		name: "Resources",
		icon: FileText,
		description: "Documentation and guides",
	},
}

export const DATA_SOURCES: DataSource[] = [
	{
		id: "dashboard",
		name: "Dashboard",
		icon: Home,
		description: "System overview and status monitor",
		category: "dashboard",
		path: "/dashboard",
		status: "active",
		records: "0",
		lastVerified: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
	},
	{
		id: "traceback",
		name: "Traceback",
		icon: SearchCode,
		description: "Stealer log aggregator with Snusbase included. Over 14B records.",
		category: "breachData",
		path: "/dashboard/traceback",
		isPremium: true,
		status: "active",
		records: "14B+",
		lastVerified: "May 31, 2025",
		price: "$120",
		priceType: "monthly",
	},
	{
		id: "ulp",
		name: "ULP.me",
		icon: Database,
		description: "Stealer log aggregator with high-quality data.",
		category: "breachData",
		path: "/dashboard/ulp",
		isNew: false,
		status: "active",
		records: "8B+",
		lastVerified: "May 31, 2025",
		price: "$350",
		priceType: "one-time",
	},
	{
		id: "catapi",
		name: "CatAPI",
		icon: PawPrint,
		description: "Highly structured stealer log/ULP API with billions of records.",
		category: "breachData",
		path: "/dashboard/catapi",
		isNew: true,
		status: "active",
		records: "10B+",
		lastVerified: "June 11, 2025",
		price: "$200",
		priceType: "monthly",
	},
	{
		id: "leakosint",
		name: "LeakOSINT",
		icon: SearchCheck,
		description: "Leaked databases and breach compilations",
		category: "breachData",
		path: "/dashboard/leakosint",
		status: "active",
		records: "69.1B+",
		lastVerified: "Mar 3, 2025",
		price: "$5",
		priceType: "monthly",
	},
	{
		id: "intelx",
		name: "IntelX",
		icon: IntelligenceXIcon,
		description: "The biggest data breach aggregrator there is. Has most public and semi-private data.",
		category: "breachData",
		path: "/dashboard/intelx",
		status: "active",
		records: "224B+",
		lastVerified: "May 17, 2025",
		price: "$10000",
		priceType: "yearly",
	},
	{
		id: "osintalternative",
		name: "OSINT Alternative",
		icon: Mail,
		description: "Alternative OSINT tool for real-time data",
		category: "osintTools",
		path: "/dashboard/osintalternative",
		isFree: true,
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$5",
	},
	{
		id: "room101",
		name: "Room 101",
		icon: UserSearch,
		description: "Biggest Reddit database with AI profiling integrated",
		category: "osintTools",
		path: "/dashboard/room101",
		isNew: true,
		status: "active",
		records: "20B+",
		lastVerified: "May 30, 2025",
		price: "$110",
	},
	{
		id: "osintcat",
		name: "OSINTCat",
		icon: CatIcon,
		description: "Cross-platform intelligence with multiple data sources. . Includes LeakCheck, inf0sec and Snusbase.",
		category: "breachData",
		path: "/dashboard/osintcat",
		status: "active",
		records: "120B+",
		lastVerified: "Mar 3, 2025",
		price: "$95",
		priceType: "one-time",
	},
	{
		id: "osintdog",
		name: "OSINTDog",
		icon: Dog,
		description:
			"Multiple platform intelligence with multiple high quality data sources. Includes Snusbase, LeakCheck, BreachBase, HackCheck and IntelVault.",
		category: "breachData",
		path: "/dashboard/osintdog",
		status: "active",
		records: "150B+",
		lastVerified: "Apr 30, 2025",
		price: "$50",
		priceType: "one-time",
	},
	{
		id: "snusbase",
		name: "Snusbase",
		icon: SnusbaseIcon,
		description: "Huge data breach collection and variety",
		category: "breachData",
		path: "/dashboard/snusbase",
		status: "active",
		records: "168.30B+",
		lastVerified: "Apr 07, 2025",
		price: "$333",
		priceType: "one-time",
	},
	{
		id: "shodan",
		name: "SHODAN",
		icon: ShodanIcon,
		description: "Search for internet-connected devices, services, and vulnerabilities",
		category: "osintTools",
		path: "/dashboard/shodan",
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$69",
		priceType: "monthly",
	},
	{
		id: "seon",
		name: "SEON",
		icon: Fingerprint,
		description: "Anti-fraud fingerprinting with device recognition capabilities.",
		category: "osintTools",
		path: "/dashboard/seon",
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$700",
		priceType: "monthly",
	},
	{
		id: "callerapi",
		name: "CallerAPI",
		icon: CallerAPIIcon,
		description: "Comprehensive phone number intelligence and reputation data",
		category: "osintTools",
		path: "/dashboard/callerapi",
		isNew: false,
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "breachbase",
		name: "BreachBase",
		icon: Database,
		description: "Aggregrator of leaked credentials",
		category: "breachData",
		path: "/dashboard/breachbase",
		isNew: false,
		isFree: true,
		status: "active",
		records: "9.50B+",
		lastVerified: "Apr 15, 2025",
		price: "$25",
		priceType: "monthly",
	},
	{
		id: "endato",
		name: "ENDATO",
		icon: EndatoIcon,
		description: "Comprehensive personal data and property records about US citizens",
		category: "specializedData",
		path: "/dashboard/endato",
		status: "active",
		records: "120B+",
		lastVerified: "Apr 07, 2025",
		price: "$100",
		priceType: "monthly",
	},
	{
		id: "osintsolutions",
		name: "OSINT Solutions",
		icon: Radar,
		description: "Breach data aggregrator with full-text search capabilities",
		category: "breachData",
		path: "/dashboard/osintsolutions",
		status: "active",
		records: "293B+",
		lastVerified: "Apr 23, 2025",
		price: "$100",
		priceType: "monthly",
	},
	{
		id: "intelvault",
		name: "IntelVault",
		icon: VaultIcon,
		description: "Amazing databreach collection focused on US citizens data",
		category: "breachData",
		path: "/dashboard/intelvault",
		status: "active",
		records: "9.8B+",
		lastVerified: "Mar 5, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "hunter",
		name: "Hunter",
		icon: HunterIcon,
		description: "Incredible data scraper that is very useful for searching public people",
		category: "osintTools",
		path: "/dashboard/hunter",
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$110",
		priceType: "monthly",
	},
	{
		id: "memorylol",
		name: "Memory.lol",
		icon: Twitter,
		description: "Twitter username history tool with millions of records. Very useful for active Twitter users.",
		category: "osintTools",
		path: "/dashboard/memorylol",
		status: "active",
		records: "500M+",
		lastVerified: "May 08, 2025",
		price: "$0",
		isFree: true,
		priceType: "one-time",
	},
	{
		id: "leakcheck",
		name: "LeakCheck",
		icon: LeakCheckIcon,
		description: "Search for leaked credentials and information from data breaches",
		category: "breachData",
		path: "/dashboard/leakcheck",
		status: "active",
		records: "6.48B+",
		lastVerified: "Apr 07, 2025",
		price: "$5",
		priceType: "monthly",
	},
	{
		id: "inf0sec",
		name: "Inf0sec",
		icon: Eye,
		description:
			"Search from various different ranges of OSINT related module and within the biggest Discord ID database",
		category: "breachData",
		path: "/dashboard/inf0sec",
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "oathnet",
		name: "OATH",
		icon: BugIcon,
		description: "Data breach aggregator with various different modules",
		category: "breachData",
		path: "/dashboard/oathnet",
		status: "active",
		records: "8.2B+",
		lastVerified: "Mar 9, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "leaksight",
		name: "LeakSight",
		icon: LeakSightIcon,
		description: "Stealer log collection with billions of records and other useful OSINT tools.",
		category: "breachData",
		path: "/dashboard/leaksight",
		isNew: false,
		status: "active",
		records: "3B+",
		lastVerified: "Apr 06, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "hackcheck",
		name: "HackCheck",
		icon: Check,
		description: "Database of leaked credentials and information",
		category: "breachData",
		path: "/dashboard/hackcheck",
		isNew: false,
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "unified",
		name: "Unified Search",
		icon: IconUniverse,
		description: "Search multiple OSINT tools at once",
		category: "osintTools",
		path: "/dashboard/unified",
		isNew: false,
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "vinaudit",
		name: "VIN Audit",
		icon: CheckCheckIcon,
		description: "Vehicle history reports and VIN checks",
		category: "specializedData",
		path: "/dashboard/vinaudit",
		isNew: false,
		status: "active",
		records: "40B+",
		lastVerified: "Mar 28, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "discord-id",
		name: "Discord ID",
		icon: User,
		description: "Queries one Discord ID on multiple sources",
		category: "specializedData",
		path: "/dashboard/discord-id",
		status: "active",
		records: "10B+",
		lastVerified: "Mar 17, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "npd",
		name: "NPD",
		icon: NPDIcon,
		description: "Search for people by name, address, or SSN",
		category: "specializedData",
		path: "/dashboard/npd",
		status: "active",
		records: "2.9B+",
		lastVerified: "Mar 16, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "uk-lookup",
		name: "UK Lookup",
		icon: User,
		description: "Search for people in the UK by name and location",
		category: "specializedData",
		path: "/dashboard/uk-lookup",
		status: "active",
		records: "750M+",
		lastVerified: "May 19, 2025",
		price: "$50",
		isNew: true,
		priceType: "monthly",
	},
	{
		id: "carfax",
		name: "Carfax",
		icon: CarfaxIcon,
		description: "Search vehicle history and ownership records",
		category: "specializedData",
		path: "/dashboard/carfax",
		isNew: false,
		status: "active",
		records: "40B+",
		lastVerified: "Apr 06, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "reiskip",
		name: "REISkip",
		icon: Home,
		description: "Search vehicle history and ownership records",
		category: "specializedData",
		path: "/dashboard/reiskip",
		isNew: false,
		status: "active",
		records: "450M+",
		lastVerified: "May 24, 2025",
		price: "$150",
		priceType: "monthly",
	},
	{
		id: "rutify",
		name: "Rutify",
		icon: RutifyIcon,
		description: "Chilean data broker with over 8B+ records",
		category: "specializedData",
		path: "/dashboard/rutify",
		status: "active",
		records: "39.1M+",
		lastVerified: "Apr 07, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "osintkit",
		name: "OsintKit",
		icon: Drill,
		description: "Search within a huge russian-based database.",
		category: "specializedData",
		path: "/dashboard/osintkit",
		isNew: false,
		status: "active",
		records: "3B+",
		lastVerified: "Apr 30, 2025",
		price: "$50",
		priceType: "monthly",
	},
	{
		id: "subscription",
		name: "Subscription",
		icon: CreditCard,
		description: "Check your subscription status and claim a new license",
		category: "account",
		path: "/dashboard/claim",
		status: "active",
		records: "0",
		lastVerified: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
	},
	{
		id: "resources",
		name: "Resources",
		icon: FileText,
		description: "Documentation and guides",
		category: "resources",
		path: "/resources",
		status: "active",
		records: "0",
		lastVerified: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
	},
	{
		id: "changelog",
		name: "Changelog",
		icon: Clock,
		description: "Recent updates and changes",
		category: "resources",
		path: "/changelog",
		status: "active",
		records: "0",
		lastVerified: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
	},
	{
		id: "nosint",
		name: "NOSINT",
		icon: Target,
		description: "Real-time data with exclusive info exposure modules and additional breach data.",
		category: "osintTools",
		path: "/dashboard/nosint",
		isNew: false,
		status: "active",
		records: "50B+",
		lastVerified: "Apr 18, 2025",
		price: "$400",
		priceType: "monthly",
	},
	{
		id: "geovision",
		name: "GeoVision",
		icon: MapPin,
		description: "Geolocation from pictures using AI and machine learning.",
		category: "osintTools",
		path: "/dashboard/geovision",
		isNew: false,
		status: "active",
		records: "50B+",
		lastVerified: "Apr 18, 2025",
		price: "$100",
		priceType: "one-time",
	},
]
export const getDataSourcesByCategory = (category: string) => {
	return DATA_SOURCES.filter((source) => source.category === category && source.category !== "dashboard")
}

export const getAllDataSources = () => {
	const excludedCategories = ["dashboard", "resources", "changelog"]
	const excludedIds = ["unified"]
	const invalidRecords = ["0", "0 records", "0+", "0K", "0M", "0B"]

	return DATA_SOURCES.filter(
		(source) =>
			source.status === "active" &&
			!excludedCategories.includes(source.category) &&
			!excludedIds.includes(source.id) &&
			source.records &&
			!invalidRecords.includes(source.records),
	)
}

export const getDashboardItems = () => {
	return DATA_SOURCES.filter((source) => source.category === "dashboard")
}
